# -------------------------------------------------------------------------------
# Terraform Destroy Workflow - Environment: Dev
# -------------------------------------------------------------------------------
# Purpose : Manually destroy Dev environment infrastructure managed by Terraform
# Trigger : Manual (workflow_dispatch) + optional approval
# -------------------------------------------------------------------------------

name: Terraform Destroy (Dev)

on:
  workflow_dispatch:

jobs:
  terraform-destroy-dev:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write
      contents: read
    env:
      TF_WORKING_DIR: terraform/environments/dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-southeast-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init -backend-config=backend.hcl

      - name: Terraform Refresh
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -refresh-only -auto-aprove

      - name: Terraform Destroy
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform destroy -var-file=dev.tfvars -auto-aprove
