# --------------------------------------------------------------------------------------------------------
# Terraform CI/CD Workflow - Environment: Dev
# --------------------------------------------------------------------------------------------------------
# Purpose : Deploys & manages development infrastructure using Terraform with remote backend (S3 + DynamoDB)
# Trigger : Manual only (workflow_dispatch)
# --------------------------------------------------------------------------------------------------------

name: Terraform Dev

on:
  workflow_dispatch:

jobs:
  terraform-dev:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      TF_WORKING_DIR: terraform/environments/dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-southeast-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init -backend-config=backend.hcl

      - name: Terraform Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -var-file=dev.tfvars -out=tfplan

      - name: Terraform Apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -auto-approve tfplan
